'use client';

import { type CSSProperties, useEffect, useState } from 'react';
import './card-polls-panel.css';

type Option = { id: string; title: string; votes: number; voted: boolean };
type Poll = { id: string; question: string; created_by: string; created_at: string; options: Option[] };
function headers() { const token = document.cookie.split('; ').find((item) => item.startsWith('flowboard_csrf='))?.slice('flowboard_csrf='.length); return token ? { 'Content-Type': 'application/json', 'x-flowboard-csrf': decodeURIComponent(token) } : { 'Content-Type': 'application/json' }; }

export default function CardPollsPanel({ cardId, canEdit, showPolls = true, showCreate = canEdit, hideWhenEmpty = false }: { cardId: string; canEdit: boolean; showPolls?: boolean; showCreate?: boolean; hideWhenEmpty?: boolean }) {
  const [polls, setPolls] = useState<Poll[]>([]); const [question, setQuestion] = useState(''); const [options, setOptions] = useState(''); const [isCreating, setCreating] = useState(false); const [deletingPollId, setDeletingPollId] = useState<string | null>(null); const [isLoading, setLoading] = useState(true);
  const load = () => { setLoading(true); void fetch(`/v1/cards/${cardId}/polls`).then((response) => response.ok ? response.json() as Promise<Poll[]> : []).then(setPolls).finally(() => setLoading(false)); };
  useEffect(() => { setQuestion(''); setOptions(''); load(); }, [cardId]);
  const create = () => { if (!question.trim() || isCreating) return; setCreating(true); void fetch(`/v1/cards/${cardId}/polls`, { method: 'POST', headers: headers(), body: JSON.stringify({ question: question.trim(), options: options.split('\n') }) }).then((response) => response.ok ? response.json() as Promise<Poll> : Promise.reject()).then((poll) => { setPolls((current) => [poll, ...current]); setQuestion(''); setOptions(''); }).finally(() => setCreating(false)); };
  const vote = (poll: Poll, option: Option) => { void fetch(`/v1/polls/${poll.id}/vote`, { method: 'POST', headers: headers(), body: JSON.stringify({ option_id: option.id }) }).then((response) => response.ok ? response.json() as Promise<Poll> : Promise.reject()).then((updated) => setPolls((current) => current.map((item) => item.id === updated.id ? updated : item))); };
  const remove = (poll: Poll) => { if (deletingPollId || !window.confirm(`Удалить голосование «${poll.question}»? Все голоса тоже будут удалены.`)) return; setDeletingPollId(poll.id); void fetch(`/v1/cards/${cardId}/polls/${poll.id}`, { method: 'DELETE', headers: headers() }).then((response) => { if (!response.ok) throw new Error('delete failed'); setPolls((current) => current.filter((item) => item.id !== poll.id)); }).catch(() => window.alert('Не удалось удалить голосование')).finally(() => setDeletingPollId(null)); };
  if (!showPolls && !showCreate) return null;
  if (hideWhenEmpty && showPolls && !showCreate && !polls.length) return null;
  return <section className={`card-polls-panel ${showPolls ? '' : 'card-polls-composer-only'}`} aria-live="polite">{showPolls && <>{isLoading ? <div className="poll-skeletons" aria-label="Загружаем голосования"><i /><i /></div> : polls.map((poll) => { const total = poll.options.reduce((sum, option) => sum + option.votes, 0); const ownVote = poll.options.find((option) => option.voted); return <article key={poll.id} className="poll-card"><header><span className="poll-kind">Голосование</span><span className="poll-total">{total} {total === 1 ? 'голос' : total > 1 && total < 5 ? 'голоса' : 'голосов'}</span>{canEdit && <button className="poll-delete" type="button" disabled={deletingPollId === poll.id} onClick={() => remove(poll)} title="Удалить голосование" aria-label={`Удалить голосование «${poll.question}»`}>×</button>}</header><div className="poll-title-row"><b>{poll.question}</b><small>@{poll.created_by} · {new Date(poll.created_at).toLocaleDateString('ru-RU')}</small></div><div className="poll-options">{poll.options.map((option) => { const percent = total ? Math.round(option.votes / total * 100) : 0; return <button type="button" className={option.voted ? 'voted' : ''} onClick={() => vote(poll, option)} key={option.id} aria-pressed={option.voted}><i style={{ '--poll-percent': `${percent}%` } as CSSProperties} /><span>{option.title}</span><em>{percent}%</em><small>{option.votes}</small></button>; })}</div>{ownVote && <footer>Ваш голос: <b>{ownVote.title}</b></footer>}</article>; })}{!isLoading && !polls.length && !hideWhenEmpty && <p className="poll-empty">Голосований пока нет.</p>}</>}{canEdit && showCreate && <form className="poll-create-form" onSubmit={(event) => { event.preventDefault(); create(); }}><div><b>Новое голосование</b><small>Варианты — по одному на строку.</small></div><input value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={300} placeholder="Вопрос для команды" /><textarea value={options} onChange={(event) => setOptions(event.target.value)} placeholder={'Вариант 1\nВариант 2'} /><button disabled={isCreating || !question.trim()}>{isCreating ? 'Создаём…' : 'Создать голосование'}</button></form>}</section>;
}
